trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  newVersion: '4.2.10.1'

steps:
- checkout: self
  lfs: true
  clean: true

- task: PowerShell@2
  displayName: 'Modify PublicVersion'
  inputs:
    targetType: 'inline'
    script: |
      $file = "sources/shared/SharedAssemblyInfo.cs"
      $content = Get-Content $file -Raw
      $content = $content -replace 'public const string PublicVersion = "4\.2\.1\.1";', 'public const string PublicVersion = "$(newVersion)";'
      Set-Content $file $content -NoNewline
      Get-Content $file | Select-String -Pattern "PublicVersion"

- task: UseDotNet@2
  displayName: 'Install .NET 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: MSBuild@1
  displayName: 'Build Assembly Processor'
  inputs:
    solution: 'sources/core/Stride.Core.AssemblyProcessor/Stride.Core.AssemblyProcessor.csproj'
    msbuildArguments: '/restore /p:Configuration=$(buildConfiguration)'
    configuration: '$(buildConfiguration)'

- task: MSBuild@1
  displayName: 'Build Stride Solution'
  inputs:
    solution: 'build/Stride.sln'
    msbuildArguments: '-restore -m:1 -nr:false -v:m -p:WarningLevel=0 -p:Configuration=$(buildConfiguration) -p:StridePlatforms=Windows -p:StrideGraphicsApiDependentBuildAll=true -p:StrideSkipUnitTests=true -p:StrideSkipAutoPack=true'
    configuration: '$(buildConfiguration)'
    maximumCpuCount: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: 'Bin/Windows/$(buildConfiguration)'
    ArtifactName: 'stride-build'
  condition: succeeded()